name: Deploy on Push

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Execute SSH Commands
        uses: GPTED/SSH-My-Action@0.1
        with:
          HOST: 188.134.91.116
          USER: bot_dev
          PORT: 2222
          PRIVATE_KEY: ${{ secrets.BOT_DEV_SSH_PRIVATE_KEY }}
          CMD: |
            cd /srv/bots/tg-askis/app/source;
            git reset --hard HEAD;
            git pull;
            cd /srv/bots;
            podman-compose up -d --build --force-recreate;
